### ISSUE TITLE
dsp/convol/cmplx: expects import "zikichombo.org/dsp/cmplx"

### ISSUE THREAD

**Issue by mewmew** [zikichombo/dsp#6]
What is the intended import path of the `cmplx` package, and what is the intended location for it in the git repository? Currently, these to seem to be in disagreement with one another.

```
u@x61s ~/g/s/z/dsp> go get zikichombo.org/dsp/...
can't load package: package zikichombo.org/dsp/convol/cmplx: code in directory /home/u/goget/src/zikichombo.org/dsp/convol/cmplx expects import "zikichombo.org/dsp/cmplx"
```

**Comment by wsc1** [comment]
Thanks again! just pushed the fix
