### ISSUE TITLE
dsp/dct: test build failed; undefined: audio, undefined: ops.Slurp

### ISSUE THREAD

**Issue by mewmew** [zikichombo/dsp#8]
At rev f6368de03a61bab9005371ee7aad31bbc756fbbf

```
u@x61s ~/g/s/z/d/dct> go test -count=1 zikichombo.org/dsp/dct
# zikichombo.org/dsp/dct
./plot_test.go:19:8: undefined: audio
./plot_test.go:26:3: undefined: ops.Slurp
FAIL	zikichombo.org/dsp/dct [build failed]
```

**Comment by mewmew** [comment]
Also, the `dsp/dct/plot_test.go` references a test data file missing from the Git repo: `/Users/scott/Dev/dawg/snd/Happy14/0.wav`

**Comment by wsc1** [comment]
Thanks again ,  you are catching lots of issues from the refactoring to the zikichombo name.
